/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller
import ConjuntosDifusos._

object App {
  def main(args: Array[String]): Unit = {
    // Crear dos conjuntos difusos "grande" con distintos parámetros
    val grande1 = grande(1, 2)
    val grande2 = grande(3, 4)

    // Crear conjuntos nuevos usando operaciones difusas
    val unionGrande = union(grande1, grande2)
    val interseccionGrande = interseccion(grande1, grande2)
    val complementoGrande1 = complemento(grande1)

    val valores = List(1, 5, 10, 50, 100)

    println("\nGrados de pertenencia al conjunto 'grande1':")
    for (v <- valores) {
      println(s"$v -> ${pertenece(v, grande1)}")
    }

    println("\nGrados de pertenencia al conjunto 'grande2':")
    for (v <- valores) {
      println(s"$v -> ${pertenece(v, grande2)}")
    }

    println("\nGrados de pertenencia a la UNION de grande1 y grande2:")
    for (v <- valores) {
      println(s"$v -> ${pertenece(v, unionGrande)}")
    }

    println("\nGrados de pertenencia a la INTERSECCIÓN de grande1 y grande2:")
    for (v <- valores) {
      println(s"$v -> ${pertenece(v, interseccionGrande)}")
    }

    println("\nGrados de pertenencia al COMPLEMENTO de grande1:")
    for (v <- valores) {
      println(s"$v -> ${pertenece(v, complementoGrande1)}")
    }
  }

  def greeting(): String = "Hello, world!"
}


